name: Make PPTX

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt install pandoc
        make
        mv pptx/nova-tto-phys-ch1.pptx pptx/nova-tto-phys-ch1-${{ github.event.release.tag_name }}.pptx
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "pptx/*"

