name: Make PPTX

on: 
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install pandoc
    - run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "pptx/*"

